@startuml

skinparam sequenceMessageAlign center

title Case Found & Signed Up For Reminder

User -> Server: 01-AB-23456
Server -> User: We found case "01-AB-23456" on 7/28/2022 1:00 PM @ Family/Criminal Courtroom 2A Chittenden, VT.\nReply with YES if you would like a courtesy reminder the day before or reply with NO to start over.
User -> Server: Yes
Server -> User: Reminder set for case (01-AB-23456)

@enduml